In [14]:
import requests

In [15]:
## Obtenido de The Movie Database (TMDB).
base_url = "https://devsapihub.com"
endpoint = "/api-movies" 

respuesta_api = requests.get(base_url + endpoint)

In [16]:
import pandas as pd
print(respuesta_api.status_code)

200

In [17]:
## Almacenar la respuesta en Json en una variable
respu_json = respuesta_api.json()  
df_api = pd.DataFrame.from_dict(respu_json)

In [18]:
df_api.info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           30 non-null     int64
 1   title        30 non-null     str
 2   description  30 non-null     str
 3   year         30 non-null     int64
 4   image_url    30 non-null     str
 5   genre        30 non-null     object
 6   stars        30 non-null     float64
dtypes: float64(1), int64(2), object(1), str(3)
memory usage: 1.8+ KB

In [19]:
## Vizualizar la información
df_api.head()

,id,title,description,year,image_url,genre,stars
0,1,The Shawshank Redemption,Two imprisoned men bond over a number of years...,1994,https://devsapihub.com/img-movies/1.jpg,[Drama],5.0
1,2,Jumanji,"In Jumanji: The Next Level, the gang is back b...",2019,https://devsapihub.com/img-movies/2.jpg,"[Adventure, Fantasy, Comedy]",3.4
2,3,The Godfather,The aging patriarch of an organized crime dyna...,1972,https://devsapihub.com/img-movies/3.jpg,"[Crime, Drama]",2.8
3,4,The Godfather: Part II,The early life and career of Vito Corleone in ...,1974,https://devsapihub.com/img-movies/4.jpg,"[Crime, Drama]",4.3
4,5,The Dark Knight,When the menace known as the Joker wreaks havo...,2008,https://devsapihub.com/img-movies/5.jpg,"[Action, Crime, Drama]",4.0

In [20]:
## para convertir el genre en vez de objeto en texto    
df_api['genre'] = df_api['genre'].apply(lambda x: ', '.join(x) if isinstance(x, list) else x)

In [21]:
## Eliminar la colunma de la imagen de portada, ya que no la necesitan.
df_api = df_api.drop(columns=['image_url'])

In [22]:
## Para eliminar posibles duplicados y guardar los cambios en una variable nueva.
df_limpio = df_api.drop_duplicates()

In [23]:
# Para cambiar los nombres de las columnas de inglés a español para que e la presentación concuerde el idioma con la información.
cambio_nom = {
    'id': 'Id',
    'title': 'Título',
    'description': 'Descripción',
    'year': 'Año',
    'genre': 'Genero',
    'stars': 'Puntuación'  
}


cambio = df_limpio.rename(columns=cambio_nom)

In [24]:
cambio.info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Id           30 non-null     int64
 1   Título       30 non-null     str
 2   Descripción  30 non-null     str
 3   Año          30 non-null     int64
 4   Genero       30 non-null     str
 5   Puntuación   30 non-null     float64
dtypes: float64(1), int64(2), str(3)
memory usage: 1.5 KB

In [25]:
cambio.head()

,Id,Título,Descripción,Año,Genero,Puntuación
0,1,The Shawshank Redemption,Two imprisoned men bond over a number of years...,1994,Drama,5.0
1,2,Jumanji,"In Jumanji: The Next Level, the gang is back b...",2019,"Adventure, Fantasy, Comedy",3.4
2,3,The Godfather,The aging patriarch of an organized crime dyna...,1972,"Crime, Drama",2.8
3,4,The Godfather: Part II,The early life and career of Vito Corleone in ...,1974,"Crime, Drama",4.3
4,5,The Dark Knight,When the menace known as the Joker wreaks havo...,2008,"Action, Crime, Drama",4.0

In [26]:
cambio.to_csv("Peliculas_DB.csv", index=False)

print("Exportado corectamente")

Exportado corectamente