In [21]:
import requests

#### información obtenida desde: [Api Colombia](https://api-colombia.com/)

In [22]:
url_base = 'https://api-colombia.com'
endpoint = '/api/v1/Department'

respuesta_api = requests.get(url_base + endpoint)

In [23]:
# Confirmar que la solicitud fue correcta.
import pandas as pd
print(respuesta_api.status_code)

200

In [24]:
## Guardar en una variable
Answ_json = respuesta_api.json()  
Departamentos  = pd.DataFrame.from_dict(Answ_json)

In [25]:
Departamentos.head()

,id,name,description,cityCapitalId,municipalities,surface,population,phonePrefix,countryId,cityCapital,country,cities,regionId,region,naturalAreas,maps,indigenousReservations,airports
0,3,Arauca,Arauca es uno de los treinta y dos departament...,143,7,23818,304978,7,1,"{'id': 143, 'name': 'Arauca', 'description': '...",None,None,3,None,None,None,None,None
1,4,Atlántico,El Atlántico es uno de los treinta y dos depar...,144,23,3388,2804025,5,1,"{'id': 144, 'name': 'Barranquilla', 'descripti...",None,None,1,None,None,None,None,None
2,7,Boyacá,Boyacá es uno de los treinta y dos departament...,217,123,23189,1259601,8,1,"{'id': 217, 'name': 'Tunja', 'description': 'T...",None,None,5,None,None,None,None,None
3,8,Caldas,Caldas es uno de los treinta y dos departament...,337,27,7888,1036455,6,1,"{'id': 337, 'name': 'Manizales', 'description'...",None,None,5,None,None,None,None,None
4,11,Cauca,Cauca es uno de los treinta y dos departamento...,399,41,29308,1516018,2,1,"{'id': 399, 'name': 'Popayán', 'description': ...",None,None,2,None,None,None,None,None

In [26]:
Departamentos.info()

<class 'pandas.DataFrame'>
RangeIndex: 33 entries, 0 to 32
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      33 non-null     int64
 1   name                    33 non-null     str
 2   description             33 non-null     str
 3   cityCapitalId           33 non-null     int64
 4   municipalities          33 non-null     int64
 5   surface                 33 non-null     int64
 6   population              33 non-null     int64
 7   phonePrefix             33 non-null     str
 8   countryId               33 non-null     int64
 9   cityCapital             33 non-null     object
 10  country                 0 non-null      object
 11  cities                  0 non-null      object
 12  regionId                33 non-null     int64
 13  region                  0 non-null      object
 14  naturalAreas            0 non-null      object
 15  maps                    0 non-null      object
 16  indigenousReservations  0 non-null      object
 17  airports                0 non-null      object
dtypes: int64(7), object(8), str(3)
memory usage: 4.8+ KB

In [27]:
# Seleccionamos solo las columnas que contienen datos
colum_necesarias = [
    "id",
    "name",
    "description",
    "cityCapitalId",
    "municipalities",
    "surface",
    "population",
    "phonePrefix",
    "regionId",
    "countryId",
    "cityCapital",
]

Departamentos_cle = Departamentos[colum_necesarias].copy()

In [28]:
# renombrar los titulos de las columnas al español para mantener una integridad linguistica en la presentación.
cambio_nombres = {
    "id": "Id",
    "name": "Departamento",
    "description": "Descripción",
    "cityCapitalId": "Id_Capital",
    "municipalities": "Total_Municipios",
    "surface": "Superficie_km2",
    "population": "Población",
    "phonePrefix": "Prefijo_Telefónico",
    "regionId": "Id_Región",
    "countryId" : "Id_país",
    "cityCapital" : "ciudad_capital", 
}

Departamentos_cle = Departamentos_cle.rename(columns=cambio_nombres)

In [29]:
# 3. Eliminar filas duplicadas en caso de (especificamos la búsqueda por el Id ya que esa es la llave principal y no se repite con datos diferentes)

Departamentos_cle = Departamentos_cle.drop_duplicates(subset=["Id"])

In [30]:
Departamentos_cle.info()

<class 'pandas.DataFrame'>
RangeIndex: 33 entries, 0 to 32
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Id                  33 non-null     int64
 1   Departamento        33 non-null     str
 2   Descripción         33 non-null     str
 3   Id_Capital          33 non-null     int64
 4   Total_Municipios    33 non-null     int64
 5   Superficie_km2      33 non-null     int64
 6   Población           33 non-null     int64
 7   Prefijo_Telefónico  33 non-null     str
 8   Id_Región           33 non-null     int64
 9   Id_país             33 non-null     int64
 10  ciudad_capital      33 non-null     object
dtypes: int64(7), object(1), str(3)
memory usage: 3.0+ KB

In [31]:
Departamentos_cle

,Id,Departamento,Descripción,Id_Capital,Total_Municipios,Superficie_km2,Población,Prefijo_Telefónico,Id_Región,Id_país,ciudad_capital
0,3,Arauca,Arauca es uno de los treinta y dos departament...,143,7,23818,304978,7,3,1,"{'id': 143, 'name': 'Arauca', 'description': '..."
1,4,Atlántico,El Atlántico es uno de los treinta y dos depar...,144,23,3388,2804025,5,1,1,"{'id': 144, 'name': 'Barranquilla', 'descripti..."
2,7,Boyacá,Boyacá es uno de los treinta y dos departament...,217,123,23189,1259601,8,5,1,"{'id': 217, 'name': 'Tunja', 'description': 'T..."
3,8,Caldas,Caldas es uno de los treinta y dos departament...,337,27,7888,1036455,6,5,1,"{'id': 337, 'name': 'Manizales', 'description'..."
4,11,Cauca,Cauca es uno de los treinta y dos departamento...,399,41,29308,1516018,2,2,1,"{'id': 399, 'name': 'Popayán', 'description': ..."
5,13,Chocó,Chocó es uno de los treinta y dos departamento...,467,31,46530,553519,4,2,1,"{'id': 467, 'name': 'Quibdó', 'description': '..."
6,16,Guainía,"Guainía (idioma yurí: ""Tierra de muchas aguas""...",644,2,72238,52061,8,4,1,"{'id': 644, 'name': 'Inírida', 'description': ..."
7,17,Guaviare,Guaviare es uno de los treinta y dos departame...,654,4,53460,90357,8,4,1,"{'id': 654, 'name': 'San José del Guaviare', '..."
8,18,Huila,Huila es uno de los treinta y dos departamento...,657,37,19890,1140932,8,5,1,"{'id': 657, 'name': 'Neiva', 'description': 'N..."
9,1,Amazonas,Amazonas es uno de los treinta y dos departame...,1,2,109665,82068,8,4,1,"{'id': 1, 'name': 'Leticia', 'description': 'L..."
10,22,Nariño,Nariño es uno de los treinta y dos departament...,769,64,33268,1629181,2,2,1,"{'id': 769, 'name': 'Pasto', 'description': 'P..."
11,25,Quindío,"Quindío, también llamado El Quindío, es uno de...",885,12,1845,569569,6,5,1,"{'id': 855, 'name': 'La Esperanza', 'descripti..."
12,23,Norte de Santander,Norte de Santander es uno de los treinta y dos...,870,40,21658,1651278,7,5,1,"{'id': 870, 'name': 'Cúcuta', 'description': '..."
13,24,Putumayo,Putumayo (Quechua: Putumayu) es uno de los tre...,872,13,24885,369064,8,4,1,"{'id': 872, 'name': 'Mocoa', 'description': 'M..."
14,26,Risaralda,Risaralda es uno de los treinta y dos departam...,897,14,4140,977829,6,5,1,"{'id': 897, 'name': 'Pereira', 'description': ..."
15,27,San Andrés y Providencia,"El archipiélago de San Andrés, Providencia y S...",912,2,44,65228,8,6,1,"{'id': 912, 'name': 'San Andrés', 'description..."
16,29,Sucre,Sucre es uno de los treinta y dos departamento...,1000,26,10917,972350,5,1,1,"{'id': 1000, 'name': 'Sincelejo', 'description..."
17,30,Tolima,Tolima es uno de los treinta y dos departament...,1069,47,23562,1346935,8,5,1,"{'id': 1069, 'name': 'Ibagué', 'description': ..."
18,32,Vaupés,Vaupés es uno de los treinta y dos departament...,1115,3,54135,48932,8,4,1,"{'id': 1115, 'name': 'Mitú', 'description': 'M..."
19,33,Vichada,Vichada es uno de los treinta y dos departamen...,1121,4,100242,115778,8,3,1,"{'id': 1121, 'name': 'Puerto Carreño', 'descri..."
20,2,Antioquia,Antioquia es uno de los treinta y dos departam...,12,125,63612,6887306,4,5,1,"{'id': 12, 'name': 'Medellín', 'description': ..."
21,5,Bogotá,"Bogotá, oficialmente Bogotá, Distrito Capital​...",167,1,1139,8906342,1,5,1,"{'id': 167, 'name': 'Bogotá D.C.', 'descriptio..."
22,15,Cundinamarca,Cundinamarca es uno de los 32 departamentos qu...,167,116,23071,2473634,1,5,1,"{'id': 167, 'name': 'Bogotá D.C.', 'descriptio..."
23,6,Bolívar,Bolívar es uno de los treinta y dos departamen...,210,45,25978,2236603,5,1,1,"{'id': 210, 'name': 'Cartagena', 'description'..."
24,9,Caquetá,Caquetá es uno de los treinta y dos departamen...,364,16,88965,419275,8,4,1,"{'id': 364, 'name': 'Florencia', 'description'..."
25,10,Casanare,Casanare es uno de los treinta y dos departame...,380,19,44640,442068,8,3,1,"{'id': 380, 'name': 'Yopal', 'description': 'Y..."
26,12,Cesar,Cesar es uno de los treinta y dos departamento...,441,25,22905,1341697,4,1,1,"{'id': 441, 'name': 'Valledupar', 'description..."
27,14,Córdoba,"Córdoba es uno de los 32 departamentos que, ju...",498,30,25020,1856496,4,1,1,"{'id': 498, 'name': 'Montería', 'description':..."
28,19,La Guajira,La Guajira (en wayuunaiki: Wajiira o Karibyczo...,694,15,20848,1002394,5,1,1,"{'id': 694, 'name': 'Riohacha', 'description':..."
29,20,Magdalena,Magdalena es uno de los treinta y dos departam...,709,30,23188,1463427,5,1,1,"{'id': 709, 'name': 'Santa Marta', 'descriptio..."
30,21,Meta,Meta es uno de los treinta y dos departamentos...,740,29,85635,1080706,8,3,1,"{'id': 740, 'name': 'Villavicencio', 'descript..."
31,28,Santander,Santander es uno de los treinta y dos departam...,915,87,30537,2324090,7,5,1,"{'id': 915, 'name': 'Bucaramanga', 'descriptio..."
32,31,Valle del Cauca,Valle del Cauca es uno de los treinta y dos de...,1093,42,22140,4589278,2,2,1,"{'id': 1093, 'name': 'Cali', 'description': 'C..."

In [32]:
# la columna de cuidad capitales está con bastante información que podemos individualizar
# Utilizamos el json_normalize para transformar la agrupación en columnas 
capitales = pd.json_normalize(Departamentos_cle["ciudad_capital"])

# 2. Nombrar las divisiones
capitales = capitales[["id", "name", "description"]].rename(
    columns={
        "id": "Id_Ciudad_Capital",
        "name": "Nombre_Capital",
        "description": "Descripción_Capital",
    }
)

# Unimos capitales con la base de información limpia (Departamentos_cle)
Departamentos_cle = pd.concat([Departamentos_cle, capitales], axis=1)

# Eliminamos la columna original
Departamentos_cle = Departamentos_cle.drop(columns=["ciudad_capital"])

In [33]:
Departamentos_cle

,Id,Departamento,Descripción,Id_Capital,Total_Municipios,Superficie_km2,Población,Prefijo_Telefónico,Id_Región,Id_país,Id_Ciudad_Capital,Nombre_Capital,Descripción_Capital
0,3,Arauca,Arauca es uno de los treinta y dos departament...,143,7,23818,304978,7,3,1,143,Arauca,"Arauca, cuyo nombre colonial es Villa de Santa..."
1,4,Atlántico,El Atlántico es uno de los treinta y dos depar...,144,23,3388,2804025,5,1,1,144,Barranquilla,El Área metropolitana de Barranquilla es una c...
2,7,Boyacá,Boyacá es uno de los treinta y dos departament...,217,123,23189,1259601,8,5,1,217,Tunja,"Tunja es un municipio colombiano, capital del ..."
3,8,Caldas,Caldas es uno de los treinta y dos departament...,337,27,7888,1036455,6,5,1,337,Manizales,"Manizales es un municipio colombiano, capital ..."
4,11,Cauca,Cauca es uno de los treinta y dos departamento...,399,41,29308,1516018,2,2,1,399,Popayán,"Popayán, oficialmente Asunción de Popayán es u..."
5,13,Chocó,Chocó es uno de los treinta y dos departamento...,467,31,46530,553519,4,2,1,467,Quibdó,"Quibdó es un municipio colombiano, capital del..."
6,16,Guainía,"Guainía (idioma yurí: ""Tierra de muchas aguas""...",644,2,72238,52061,8,4,1,644,Inírida,Inírida (antes llamado Puerto Inírida) es un m...
7,17,Guaviare,Guaviare es uno de los treinta y dos departame...,654,4,53460,90357,8,4,1,654,San José del Guaviare,San José del Guaviare es un municipio colombia...
8,18,Huila,Huila es uno de los treinta y dos departamento...,657,37,19890,1140932,8,5,1,657,Neiva,"Neiva es un municipio colombiano, capital del ..."
9,1,Amazonas,Amazonas es uno de los treinta y dos departame...,1,2,109665,82068,8,4,1,1,Leticia,"Leticia es un municipio fronterizo colombiano,..."
10,22,Nariño,Nariño es uno de los treinta y dos departament...,769,64,33268,1629181,2,2,1,769,Pasto,"Pasto es un municipio colombiano, capital del ..."
11,25,Quindío,"Quindío, también llamado El Quindío, es uno de...",885,12,1845,569569,6,5,1,855,La Esperanza,
12,23,Norte de Santander,Norte de Santander es uno de los treinta y dos...,870,40,21658,1651278,7,5,1,870,Cúcuta,"Cúcuta, oficialmente San José de Cúcuta, es un..."
13,24,Putumayo,Putumayo (Quechua: Putumayu) es uno de los tre...,872,13,24885,369064,8,4,1,872,Mocoa,Mocoa es un municipio colombiano y capital del...
14,26,Risaralda,Risaralda es uno de los treinta y dos departam...,897,14,4140,977829,6,5,1,897,Pereira,"Pereira es un municipio colombiano, capital de..."
15,27,San Andrés y Providencia,"El archipiélago de San Andrés, Providencia y S...",912,2,44,65228,8,6,1,912,San Andrés,"San Andrés, conocido localmente como North End..."
16,29,Sucre,Sucre es uno de los treinta y dos departamento...,1000,26,10917,972350,5,1,1,1000,Sincelejo,"Sincelejo es un municipio colombiano, capital ..."
17,30,Tolima,Tolima es uno de los treinta y dos departament...,1069,47,23562,1346935,8,5,1,1069,Ibagué,Ibagué es un municipio colombiano ubicado en e...
18,32,Vaupés,Vaupés es uno de los treinta y dos departament...,1115,3,54135,48932,8,4,1,1115,Mitú,Mitú es la capital del departamento del Vaupés...
19,33,Vichada,Vichada es uno de los treinta y dos departamen...,1121,4,100242,115778,8,3,1,1121,Puerto Carreño,"Puerto Carreño es un municipio colombiano, cap..."
20,2,Antioquia,Antioquia es uno de los treinta y dos departam...,12,125,63612,6887306,4,5,1,12,Medellín,"Medellín es un distrito colombiano, capital de..."
21,5,Bogotá,"Bogotá, oficialmente Bogotá, Distrito Capital​...",167,1,1139,8906342,1,5,1,167,Bogotá D.C.,"Bogotá, oficialmente Bogotá, Distrito Capital ..."
22,15,Cundinamarca,Cundinamarca es uno de los 32 departamentos qu...,167,116,23071,2473634,1,5,1,167,Bogotá D.C.,"Bogotá, oficialmente Bogotá, Distrito Capital ..."
23,6,Bolívar,Bolívar es uno de los treinta y dos departamen...,210,45,25978,2236603,5,1,1,210,Cartagena,"Cartagena de Indias, oficialmente Distrito Tur..."
24,9,Caquetá,Caquetá es uno de los treinta y dos departamen...,364,16,88965,419275,8,4,1,364,Florencia,"Florencia es un municipio colombiano, capital ..."
25,10,Casanare,Casanare es uno de los treinta y dos departame...,380,19,44640,442068,8,3,1,380,Yopal,"Yopal es un municipio colombiano, capital del ..."
26,12,Cesar,Cesar es uno de los treinta y dos departamento...,441,25,22905,1341697,4,1,1,441,Valledupar,"Valledupar, también llamada Ciudad de los Sant..."
27,14,Córdoba,"Córdoba es uno de los 32 departamentos que, ju...",498,30,25020,1856496,4,1,1,498,Montería,"Montería es un municipio colombiano, capital d..."
28,19,La Guajira,La Guajira (en wayuunaiki: Wajiira o Karibyczo...,694,15,20848,1002394,5,1,1,694,Riohacha,"Riohacha, oficialmente Distrito Especial, Turí..."
29,20,Magdalena,Magdalena es uno de los treinta y dos departam...,709,30,23188,1463427,5,1,1,709,Santa Marta,"Santa Marta, oficialmente Distrito Turístico, ..."
30,21,Meta,Meta es uno de los treinta y dos departamentos...,740,29,85635,1080706,8,3,1,740,Villavicencio,"Villavicencio es un municipio colombiano, capi..."
31,28,Santander,Santander es uno de los treinta y dos departam...,915,87,30537,2324090,7,5,1,915,Bucaramanga,"Bucaramanga es un municipio colombiano, capita..."
32,31,Valle del Cauca,Valle del Cauca es uno de los treinta y dos de...,1093,42,22140,4589278,2,2,1,1093,Cali,"Cali, oficialmente Distrito Especial, Deportiv..."

In [34]:
# Eliminar la fila que salio (Id_Ciudad_Capital) ya que en el formato original ya estaba en una columna inicial.
Departamentos_cle = Departamentos_cle.drop(columns=["Id_Ciudad_Capital"])

In [35]:
Departamentos_cle

,Id,Departamento,Descripción,Id_Capital,Total_Municipios,Superficie_km2,Población,Prefijo_Telefónico,Id_Región,Id_país,Nombre_Capital,Descripción_Capital
0,3,Arauca,Arauca es uno de los treinta y dos departament...,143,7,23818,304978,7,3,1,Arauca,"Arauca, cuyo nombre colonial es Villa de Santa..."
1,4,Atlántico,El Atlántico es uno de los treinta y dos depar...,144,23,3388,2804025,5,1,1,Barranquilla,El Área metropolitana de Barranquilla es una c...
2,7,Boyacá,Boyacá es uno de los treinta y dos departament...,217,123,23189,1259601,8,5,1,Tunja,"Tunja es un municipio colombiano, capital del ..."
3,8,Caldas,Caldas es uno de los treinta y dos departament...,337,27,7888,1036455,6,5,1,Manizales,"Manizales es un municipio colombiano, capital ..."
4,11,Cauca,Cauca es uno de los treinta y dos departamento...,399,41,29308,1516018,2,2,1,Popayán,"Popayán, oficialmente Asunción de Popayán es u..."
5,13,Chocó,Chocó es uno de los treinta y dos departamento...,467,31,46530,553519,4,2,1,Quibdó,"Quibdó es un municipio colombiano, capital del..."
6,16,Guainía,"Guainía (idioma yurí: ""Tierra de muchas aguas""...",644,2,72238,52061,8,4,1,Inírida,Inírida (antes llamado Puerto Inírida) es un m...
7,17,Guaviare,Guaviare es uno de los treinta y dos departame...,654,4,53460,90357,8,4,1,San José del Guaviare,San José del Guaviare es un municipio colombia...
8,18,Huila,Huila es uno de los treinta y dos departamento...,657,37,19890,1140932,8,5,1,Neiva,"Neiva es un municipio colombiano, capital del ..."
9,1,Amazonas,Amazonas es uno de los treinta y dos departame...,1,2,109665,82068,8,4,1,Leticia,"Leticia es un municipio fronterizo colombiano,..."
10,22,Nariño,Nariño es uno de los treinta y dos departament...,769,64,33268,1629181,2,2,1,Pasto,"Pasto es un municipio colombiano, capital del ..."
11,25,Quindío,"Quindío, también llamado El Quindío, es uno de...",885,12,1845,569569,6,5,1,La Esperanza,
12,23,Norte de Santander,Norte de Santander es uno de los treinta y dos...,870,40,21658,1651278,7,5,1,Cúcuta,"Cúcuta, oficialmente San José de Cúcuta, es un..."
13,24,Putumayo,Putumayo (Quechua: Putumayu) es uno de los tre...,872,13,24885,369064,8,4,1,Mocoa,Mocoa es un municipio colombiano y capital del...
14,26,Risaralda,Risaralda es uno de los treinta y dos departam...,897,14,4140,977829,6,5,1,Pereira,"Pereira es un municipio colombiano, capital de..."
15,27,San Andrés y Providencia,"El archipiélago de San Andrés, Providencia y S...",912,2,44,65228,8,6,1,San Andrés,"San Andrés, conocido localmente como North End..."
16,29,Sucre,Sucre es uno de los treinta y dos departamento...,1000,26,10917,972350,5,1,1,Sincelejo,"Sincelejo es un municipio colombiano, capital ..."
17,30,Tolima,Tolima es uno de los treinta y dos departament...,1069,47,23562,1346935,8,5,1,Ibagué,Ibagué es un municipio colombiano ubicado en e...
18,32,Vaupés,Vaupés es uno de los treinta y dos departament...,1115,3,54135,48932,8,4,1,Mitú,Mitú es la capital del departamento del Vaupés...
19,33,Vichada,Vichada es uno de los treinta y dos departamen...,1121,4,100242,115778,8,3,1,Puerto Carreño,"Puerto Carreño es un municipio colombiano, cap..."
20,2,Antioquia,Antioquia es uno de los treinta y dos departam...,12,125,63612,6887306,4,5,1,Medellín,"Medellín es un distrito colombiano, capital de..."
21,5,Bogotá,"Bogotá, oficialmente Bogotá, Distrito Capital​...",167,1,1139,8906342,1,5,1,Bogotá D.C.,"Bogotá, oficialmente Bogotá, Distrito Capital ..."
22,15,Cundinamarca,Cundinamarca es uno de los 32 departamentos qu...,167,116,23071,2473634,1,5,1,Bogotá D.C.,"Bogotá, oficialmente Bogotá, Distrito Capital ..."
23,6,Bolívar,Bolívar es uno de los treinta y dos departamen...,210,45,25978,2236603,5,1,1,Cartagena,"Cartagena de Indias, oficialmente Distrito Tur..."
24,9,Caquetá,Caquetá es uno de los treinta y dos departamen...,364,16,88965,419275,8,4,1,Florencia,"Florencia es un municipio colombiano, capital ..."
25,10,Casanare,Casanare es uno de los treinta y dos departame...,380,19,44640,442068,8,3,1,Yopal,"Yopal es un municipio colombiano, capital del ..."
26,12,Cesar,Cesar es uno de los treinta y dos departamento...,441,25,22905,1341697,4,1,1,Valledupar,"Valledupar, también llamada Ciudad de los Sant..."
27,14,Córdoba,"Córdoba es uno de los 32 departamentos que, ju...",498,30,25020,1856496,4,1,1,Montería,"Montería es un municipio colombiano, capital d..."
28,19,La Guajira,La Guajira (en wayuunaiki: Wajiira o Karibyczo...,694,15,20848,1002394,5,1,1,Riohacha,"Riohacha, oficialmente Distrito Especial, Turí..."
29,20,Magdalena,Magdalena es uno de los treinta y dos departam...,709,30,23188,1463427,5,1,1,Santa Marta,"Santa Marta, oficialmente Distrito Turístico, ..."
30,21,Meta,Meta es uno de los treinta y dos departamentos...,740,29,85635,1080706,8,3,1,Villavicencio,"Villavicencio es un municipio colombiano, capi..."
31,28,Santander,Santander es uno de los treinta y dos departam...,915,87,30537,2324090,7,5,1,Bucaramanga,"Bucaramanga es un municipio colombiano, capita..."
32,31,Valle del Cauca,Valle del Cauca es uno de los treinta y dos de...,1093,42,22140,4589278,2,2,1,Cali,"Cali, oficialmente Distrito Especial, Deportiv..."

In [36]:
Departamentos_cle.to_csv("Departamentos.csv", index=False)

print("Exportado corectamente")

Exportado corectamente